# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
 pipelines:
   - pipeline: MyAppCI
     source: UBSTest

 builds:
   - build: myJenkinsApp
     type: Jenkins
     connection: Spaceworkz
     source: UBSTest

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: Deploy
    displayName: Application deployment
    pool: hosted
    environment: Environment01
    strategy:
        runOnce:
          deploy:
            steps:
              - powershell: |
                  ls $(Pipeline.Workspace)/
              - task: AzurePowerShell@4
                inputs:
                  azureSubscription: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
                  ScriptType: 'InlineScript'
                  Inline: |
                    # You can write your azure powershell scripts inline here. 
                    echo hello world
                    # You can also pass predefined and custom variables to this script using arguments




