# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
   include:
     - master
  paths:
    exclude:
      - README.md
   

resources:
  pipelines:
    - pipeline: MyAppCI
      source: UBSTest
      branch: master

      
  builds:
  - build: javaAppBuild
    type: Jenkins
    connection: Spaceworkz
    source: UBSTest
      
variables: 
- name: foobar
  value: xyz
- group: MyVG

stages:
- stage: Build 
  displayName: Build
  jobs:
  - job: myBuild1
    pool: Hosted VS2017
    steps:
    - download: MyAppCI
    - downloadBuild: javaAppBuild
    - powershell: |
                  ls $(Pipeline.Workspace)/
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'myArt1'
    - task: DownloadGitHubRelease@0
      inputs:
        connection: 'ashokirla'
        userRepository: 'ashokirla/Fabrikam'
        defaultVersionType: 'latest'
        downloadPath: '$(System.ArtifactsDirectory)'

#      

- stage: Deploy
  displayName: Deploy stage
#  dependsOn: Build
  jobs:  
  - deployment: Deploy
    displayName: Application deployment
    pool: Hosted VS2017
    environment: Environment01
    strategy:
        runOnce:
          deploy:
            steps:
              - powershell: |
                  ls $(Pipeline.Workspace)/
              - task: DownloadGitHubRelease@0
                inputs:
                  connection: 'ashokirla'
                  userRepository: 'ashokirla/Fabrikam'
                  defaultVersionType: 'latest'
                  downloadPath: '$(System.ArtifactsDirectory)'



  - deployment: Deploy2
    displayName: Deploy2
    dependsOn: Deploy
    environment: Environment01
    pool: Hosted VS2017
    strategy:
      runOnce:
       deploy:
         steps:
           - download: none
           #- downloadBuild: none
 




